os: osx
osx_image: xcode10b
language: objective-c
install: 
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
before_script: 
  - pod lib lint --allow-warnings
  - swiftlint --strict
matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - env: NAME=SPM
script:
- |
  if [ "$NAME" = "Xcode" ]
  then
    TOOLCHAINS=`swiftenv version-name` xcodebuild test -project Crossroad.xcodeproj -scheme Crossroad -destination "${DESTINATION}"
  else
    swift test
  fi
